site_name: Beat Saber マッピング用語集
site_description: Beat Saber（ビートセイバー）のマッピングに特化した用語集。配置用語なども含みます。
site_url: https://ge2toro.github.io/bs-jpmapping-glossary/
theme:
  name: material
  language: ja
  custom_dir: overrides
  font:
    text: 
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替える  
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-3
        name: ライトモードに切り替える
nav:
  - マッピング用語集: index.md
  - リンク集: links.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ge2toro
      name: toro on X
    - icon: custom/note
      link: https://note.com/toro_desu
      name: toro on note
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gfKQkgcpmE
      name: Discord (mapping group)
    - icon: fontawesome/brands/github
      link: https://github.com/Ge2toro/bs-jpmapping-glossary
      name: GitHubリポジトリ
extra_css:
  - stylesheets/custom.css