site_name: Beat Saber マッピング用語集
theme:
  name: material
  language: ja
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替える  
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-3
        name: ライトモードに切り替える
markdown_extensions:
  - admonition               # 通常の囲み枠 (!!!) を使えるようにする
  - pymdownx.details         # 折りたたみ (???) を使えるようにする
  - pymdownx.superfences     # 枠の中にさらに表やコードを書けるようにする
plugins:
  - search
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ge2toro
      name: toro on X
    - icon: fontawesome/brands/github
      link: https://github.com/Ge2toro/bs-jpmapping-glossary
      name: GitHubリポジトリ